usuario:
    resource: "@usuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

padel:
    resource: "@PadelBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /usuario/logout
