# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        UsuarioBundle\Entity\usuarios:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 1234
                        roles: 'ROLE_ADMIN'
        my_db_provider:
            entity:
                class: usuarioBundle:usuarios
                property: username

    access_control:
    - { path: ^/admin , roles: ROLE_ADMIN }
    - { path: ^/ roles: IS_AUTHENTICATED_ANONYMOUSLY }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/usuario/admin
            http_basic: ~
        usuarios:
            pattern: ^/
            anonymous: ~
            provider: my_db_provider
            form_login:
                login_path: /usuario/login
                check_path: /usuario/login
            logout:
              path: /usuario/logout
              target: /usuario/login
        # main:
        #     anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
