padel_homepage:
    path:     /
    defaults: { _controller: PadelBundle:Default:index }
padel_partidas:
    path:     /partidas
    defaults: { _controller: PadelBundle:Default:partidas }
padel_torneos:
    path:     /jugadores
    defaults: { _controller: PadelBundle:Jugador:jugadores }
padel_nombre:
    path:     /nombre/{nombre}
    defaults: { _controller: PadelBundle:Default:nombre }
padel_nombreId:
    path:     /nombreId/{id}
    defaults: { _controller: PadelBundle:Default:nombreId }
padel_form:
    path:     /form
    defaults: { _controller: PadelBundle:Jugador:crearJugador }
padel_formMod:
    path:     /{id}
    defaults: { _controller: PadelBundle:Jugador:actualizarJugadores }
padel_delete:
    path:     /delete/{id}
    defaults: { _controller: PadelBundle:Jugador:eliminarJugador }
