<?php

namespace PadelBundle\Repository;

/**
 * jugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jugadorRepository extends \Doctrine\ORM\EntityRepository
{
}
