<?php

namespace PadelBundle\Repository;

/**
 * nivelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class nivelRepository extends \Doctrine\ORM\EntityRepository
{
}
