<?php

namespace PadelBundle\Repository;

/**
 * torneoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class torneoRepository extends \Doctrine\ORM\EntityRepository
{
}
